name: Build and deploy

on:
  push:
    branches:
      - master # or master before October 2020
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Use ruby/setup-ruby to shorten build times
      # https://github.com/ruby/setup-ruby
      #- uses: ruby/setup-ruby@v1
      #  with:
      #    ruby-version: 2.7 # Not needed with a .ruby-version file
      #    bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # Install Node as this is needed for PostCSS
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Install PostCSS plugins (from your package.json)
      - run: npm install
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4.2.0 /bin/bash -c "chmod -R 777 /srv/jekyll && bundle install && npm run build"
         
      # use actions-gh-pages to deploy
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GITHUB_TOKEN secret is set up automatically
          github_token: ${{ secrets.GH_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          cname: nh4.org
          publish_dir: _site
